=== chudin-nix/XMLXSD/src/test/resources/Stones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Stones" type="Stones"/>
    <xs:complexType name="Stones">
        <xs:sequence>
            <xs:element name="Topaz" type="Topaz"/>
            <xs:element name="Sapphire" type="Sapphire"/>
            <xs:element name="Brilliant" type="Brilliant"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="AbstractStone">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Type" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AbstractPreciousStone">
        <xs:complexContent>
            <xs:extension base="AbstractStone">
                <xs:sequence>
                    <xs:element name="Hardness" type="xs:double"/>
                    <xs:element name="Rarity" type="Rarity"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="AbstractNonPreciousStone">
        <xs:complexContent>
            <xs:extension base="AbstractStone">
                <xs:sequence>
                    <xs:element name="Transparency" type="Transparency"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="Transparency">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TRANSPARENT"/>
            <xs:enumeration value="NON_TRANSPARENT"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Color">
        <xs:restriction base="xs:string">
            <xs:enumeration value="WITHOUT_COLOR"/>
            <xs:enumeration value="BLUE"/>
            <xs:enumeration value="PINK"/>
            <xs:enumeration value="RED"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Form">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CABOCHON"/>
            <xs:enumeration value="TABLET"/>
            <xs:enumeration value="CRYSTALLINE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TypeStone">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PRECIOUS"/>
            <xs:enumeration value="NON_PRECIOUS"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Rarity">
        <xs:restriction base="xs:string">
            <xs:enumeration value="RARE"/>
            <xs:enumeration value="VERY_RARE"/>
            <xs:enumeration value="NON_RARE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Topaz">
        <xs:complexContent>
            <xs:extension base="AbstractNonPreciousStone">
                <xs:sequence>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Sapphire">
        <xs:complexContent>
            <xs:extension base="AbstractPreciousStone">
                <xs:sequence>
                    <xs:element name="Country" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Brilliant">
        <xs:complexContent>
            <xs:extension base="AbstractPreciousStone">
                <xs:sequence>
                    <xs:element name="Color" type="Color"/>
                    <xs:element name="Form" type="Form"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== chudin-nix/XMLXSD/src/test/resources/EmptyFieldsStones.xml
<?xml version="1.0" encoding="utf-8"?>
<Stones xsi:noNamespaceSchemaLocation="Stones.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="file://D:/Обучение/Java/Projects/XMLXSD/src/test/resources/Stones.xsd">
    <Topaz>
        <Name>Null</Name>
        <Type>Null</Type>
        <Transparency>Null</Transparency>
    </Topaz>
    <Sapphire>
        <Name>Null</Name>
        <Type>Null</Type>
        <Hardness>Null</Hardness>
        <Rarity>Null</Rarity>
        <Country>Null</Country>
    </Sapphire>
    <Brilliant>
        <Name>Null</Name>
        <Type>Null</Type>
        <Hardness>Null</Hardness>
        <Rarity>Null</Rarity>
        <Color>Null</Color>
        <Form>Null</Form>
    </Brilliant>
</Stones>

=== chudin-nix/XMLXSD/src/test/resources/Stones.xml
<?xml version="1.0" encoding="utf-8"?>
<Stones xsi:noNamespaceSchemaLocation="Stones.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="file://D:/Обучение/Java/Projects/XMLXSD/src/test/resources/Stones.xsd">
    <Topaz>
        <Name>Blue Topaz</Name>
        <Type>NON_PRECIOUS</Type>
        <Transparency>TRANSPARENT</Transparency>
    </Topaz>
    <Sapphire>
        <Name>Corundum</Name>
        <Type>PRECIOUS</Type>
        <Hardness>-42640699999999.8</Hardness>
        <Rarity>NON_RARE</Rarity>
        <Country>USA</Country>
    </Sapphire>
    <Brilliant>
        <Name>Round Diamond</Name>
        <Type>PRECIOUS</Type>
        <Hardness>-42640699999999.8</Hardness>
        <Rarity>NON_RARE</Rarity>
        <Color>BLUE</Color>
        <Form>CABOCHON</Form>
    </Brilliant>
</Stones>
